Dev/ci project
cpp-park-vk-education/2022_2_24-7 pull request #2
Opened 2022-10-24 14:33 UTC by KolobokMysnoy

ДЗ1

2022-11-20 11:25 UTC, Arugaf requested changes

2022-11-20 11:25 UTC, Arugaf commented on .github/workflows/CI.yml
> +      - main
Запускается по 2 раза.

2022-11-20 11:25 UTC, Arugaf commented on .github/workflows/CI.yml
> +      - 'dev/*'
**

2022-11-20 11:25 UTC, Arugaf commented on .github/workflows/CI.yml
> +        run: python checkFiles.py
Что такое check files? Не очень понятно по названию что должно происходить.

2022-11-20 11:25 UTC, Arugaf commented on .github/workflows/CI.yml
> +        run: python checkFiles.py
Нет clang format и clang-tidy.

2022-11-20 11:25 UTC, Arugaf commented on .github/workflows/CI.yml
> +          cmake --build build
?

2022-11-20 11:25 UTC, Arugaf commented on .github/workflows/CI.yml
> +        working-directory: build
Все еще не прикрепляется отчет о покрытии к пр.

2022-11-20 11:25 UTC, Arugaf commented on CMakeLists.txt
> +set(PROJECT_NAME "joint_viewing")
joint viewing?

Придумайте нормальное название для проекта. Совместный - mutual.

2022-11-20 11:25 UTC, Arugaf commented on CMakeLists.txt
> +set(TestDirecotries "tests")
Опечатка + сомнительная переменная.

2022-11-20 11:25 UTC, Arugaf commented on CMakeLists.txt
> +set(Executables "client/src/main.cpp")
Очень сомнительная переменная.

2022-11-20 11:25 UTC, Arugaf commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Корневой cmake, вероятно, не имеет смысла тут указывать версию плюсов.

2022-11-20 11:25 UTC, Arugaf commented on CMakeLists.txt
> +add_executable(${PROJECT_NAME} ${Executables})
И собирать бинарники тоже.

2022-11-20 11:25 UTC, Arugaf commented on CMakeLists.txt
> +target_include_directories(${PROJECT_NAME} PUBLIC ${Project_INCLUDE_DIRS})
И линковать либы.

2022-11-20 11:25 UTC, Arugaf commented on CPPLINT.cfg
> +filter=-readability/casting
Так и не поправлено.

2022-11-20 11:25 UTC, Arugaf commented on Dockerfile
> +    make install
Не используется.

2022-11-20 11:25 UTC, Arugaf commented on client/CMakeLists.txt
> +set(PROJECT_NAME "client")
Просто client?

2022-11-20 11:25 UTC, Arugaf commented on client/CMakeLists.txt
> +set(SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp)
${CMAKE_CURRENT_SOURCE_DIR} избыточно.

2022-11-20 11:25 UTC, Arugaf commented on client/include/main.hpp
> +
?

2022-11-20 11:25 UTC, Arugaf commented on libs/CMakeLists.txt
> +set(PROJECT_NAME "Libraries")
?

2022-11-20 11:25 UTC, Arugaf commented on libs/CMakeLists.txt
> +set(Project_INCLUDE_DIRS ${Project_INCLUDE_DIRS} PARENT_SCOPE)
Почему родительский скоуп?

2022-11-20 11:25 UTC, Arugaf commented on tests/CMakeLists.txt
> +)
Может загружаться даже если уже есть в системе.

2022-11-23 16:18 UTC, ned8800 commented
format_check.sh некорректно запускается на docker у Игната

2022-11-28 11:49 UTC, Arugaf approved these changes
Есть некоторые довольно важные проблемы (например то, что касается тестов), но в целом можно вливать.

* Геворк: 8 баллов
* Ринат: 8 баллов
* Игнат: 9 баллов
* Тимофей: 8 баллов

2022-11-28 11:49 UTC, Arugaf commented on .vscode/settings.json
> +        "any": "cpp",
Лишний файл?

2022-11-28 11:49 UTC, Arugaf commented on CMakeLists.txt
> +OPTION(BUILD_SANITIZE "Sanitize" OFF)
Мешанина стилей.

2022-11-28 11:49 UTC, Arugaf commented on CMakeLists.txt
> +string(APPEND CMAKE_CXX_FLAGS " -Wlogical-op  -Wduplicated-cond -Wcast-qual -Wcast-align")
Вообще конечно есть директива add_compile_options... А тут как-то совсем странно.

2022-11-28 11:49 UTC, Arugaf commented on CMakeLists.txt
> +endif()
Лучше не or, а включать соответствующую опцию если включен BUILD_ALL.

2022-11-28 11:49 UTC, Arugaf commented on CMakeLists.txt
> +    add_test(tests_client_side "./client_side/tests_client_side/testsForClientSide")
Захардкожено. Такого быть не должно.

2022-11-28 11:49 UTC, Arugaf commented on CMakeLists.txt
> +    string(APPEND CMAKE_CXX_FLAGS " -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-undefined-trap-on-error")
Кажется в CI этот флаг не используется?

2022-11-28 11:49 UTC, Arugaf commented on CMakeLists.txt
> +    string(APPEND CMAKE_CXX_FLAGS " -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-undefined-trap-on-error")
И все же лучше тогда уж через SET.

2022-11-28 11:49 UTC, Arugaf commented on CPPLINT.cfg
> +linelength=80
Маловато будет? Не в 70-х сидим же.

2022-11-28 11:49 UTC, Arugaf commented on scripts/cpplint_check.sh
> +print_lint_header "SUCCESS"
Пустые строки надо бы добавить.

2022-11-28 11:49 UTC, Arugaf commented on server_side/text_editor/tests_text_editor/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
А вот это уже странно. Зачем делать это для каждого модуля?

2022-12-19 20:59 UTC, merged