Dev/ignat e/editor
cpp-park-vk-education/2022_2_24-7 pull request #4
Opened 2022-11-21 14:21 UTC by KolobokMysnoy

2022-12-12 14:22 UTC, KolobokMysnoy commented
Роменский Игнат WEB-13

2022-12-20 22:13 UTC, Arugaf requested changes
Не используются неймспейсы.

Большая беда (!!!) с семантической составляющей: по сигнатурам функций/методов, названиям классов невозможно понять что они должны делать

Интенсивное использование сырых указателей :(

С форматированием все тоже очень плохо. Кажется, что все 1 дз было сделано зря.

В большинстве тестов отсутствует структура. Некоторые тесты просто огромные и вних либо вообще ничего не тестируется, либо тестируется сразу несколько вещей. Нет разделения на негативные и позитивные сценарии.

По UML: все опять же упирается в семантику. Какая-то работа над декомпозицией хоть и была сделана, но паттерны проектирования не используются, нарушаются принципы SOLID, некоторые классы явно знают про то, о чем знать не должны. WorkWithLineText явно является каким-то божественным классом, которые делает сразу много различных вещей.

Каркас и тесты: 4
UML: 5

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/.clang-format
> +# BasedOnStyle:  Google
Уже третий clang-format конфиг. Непонятно почему.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +#include "element.hpp"
Между pragma once и остальным содержимым файла ставится пустая строка.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +#include "element.hpp"
forward declaration > include.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +bool checkForBeforeLess(Element* elementBefore, Element* elementAfter);
Совсем неудачные сигнатуры функций. По ним абсолютно непонятно что они делают.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +};
В целом какие-то большие проблемы с семантикой.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +struct checkForNotEqual: public IcheckForLessOrEqual {
Отсутствует единство стиля.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +};
Один файл - один класс...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +    bool  func(Element* elementBefore, Element* elementAfter) override;
С форматированием большая беда.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/Functors.hpp
> +    bool  func(Element* elementBefore, Element* elementAfter) override;
Почему сырые указатели?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/SearcherForPlace.hpp
> +class Searcher : public ISearchForPlace {
Что Searcher? Ничего непонятно.

Интерфейс ISearchForPlace тоже ни о чем не говорит. Да и название выглядит больше похожим на функцию, чем на класс.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/SearcherForPlace.hpp
> +    AnswerForLineAndElementVisible searchForLineAndPos(Element* start, Element* compareElement, StartOfLine* line, IcheckForLessOrEqual* func) override;
[[nodiscard]]

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/SearcherForPlace.hpp
> +    AnswerForInsertAction whatPositionDelete(Element* elementToDelete, Element* beggining, StartOfLine* lines) override;
whatPositionDelete - выглядит скорее как название аргумента, чем метода...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/SearcherForPlace.hpp
> +    virtual ~Searcher() = default;
virtual деструктор должен быть указан в классе интерфейсе, а не в классе наследнике...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +#include "SearcherForPlace.hpp"
В чем логика порядка данных инклюдов?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +class WorkWithLines : public IWorkWithText {
Очень неудачные названия классов повсюду.

WorkWithLines, WorkWithText - слишком обобщенные названия которые нисколько не отражают зону ответственности данного класса.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +    std::string deleteElementFromPosition(std::string command) override;
Почему логика для клиента и сервера различается?

Если даже это обосновано, то почему клиент или сервер будут иметь доступ к неиспользуемой реализации?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +    std::string insertElementInPosition(size_t position, std::string symbol) override;
Очередной непонятный метод.

Почему возвращается std::string? В чем логика?

Название метода можно было сократить до insertElement, далее полагаться на нейминги аргументов в сигнатуре.

До этого был объявлен тип Element, а принимаем std::string symbol - тоже не очень логично.

std::string будет каждый раз копироваться.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +    std::string deleteElementFromPosition(std::string command) override;
Причем тут command? Методы будут сами как-то парсить "команду" или что?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +    size_t getQuantityOfLines() override;
const?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TextEditor.hpp
> +    size_t _UserId;
Почему этот класс знает что-то про юзера?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TranslatorFromList.hpp
> +    virtual ~TranslatorFromList() = default;
Повсюду виртуальные деструкторы в дочерних классах. Кажется, нужно разобраться в том как работает динамический полиморфизм...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/TranslatorFromList.hpp
> +    std::string returnStringFromDataType(Element* from) override;
Много слов - мало смысла. Использовать сочетания вида "return string" и "data type" в названии как-то странно.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/WorkWithData.hpp
> +    std::string operationWithData(std::string operation, bool isCommand = false) override; // If do on server then isCommand set True
По названию кажется, что первый аргумент будет менять свой смысл и значение в зависимости от второго аргумента - это очень странно.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/WorkWithData.hpp
> +    std::string operationWithData(std::string operation, bool isCommand = false) override; // If do on server then isCommand set True
Опять какие-то generic названия классов и методов. Почти любой класс и так работает с данными (ну и тогда уж тут должно быть существительное, а не глагол. Почему любой метод тоже как-то обрабатывает данные (и тут должен быть глагол, а не существительное).

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/WorkWithData.hpp
> +    void userFirst(size_t UserId = 0, size_t userCount = 0) override;
Очень странный метод... Непонятно что делает, да и причем тут пользователь вообще непонятно, ведь это все относится к алгоритму работы с одновременным редактированием.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/WorkWithData.hpp
> +    void addFile(std::string path) override;
Какой addFile, его addFile, опять непонятно. Зона ответственности класса абсолютно непонятна. Почему он знает что-то про файла?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/WorkWithData.hpp
> +    void addFile(std::string path) override;
std::filesystem::path?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/include/WorkWithData.hpp
> +    ~WorkWithData();
Почему не override?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/Answer.hpp
> +    AnswerForInsertAction() : quantOfElementsBefore(0) , quantOfLine(0), elementBeforeInsert(nullptr), isEnterBefore(false) {};
А нужен ли этот конструктор?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/Command.hpp
> +    Command(std::string str);
explicit?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/ISearchForPlace.hpp
> +    virtual AnswerForLineAndElementVisible searchForLineAndPos(Element* start, Element* compareElement, StartOfLine* line, IcheckForLessOrEqual* func) = 0;
Почему IcheckForLessOrEqual, кажется, должен быть не интерфейсным классом, а самым обычным функтором...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/StartOfLine.hpp
> +    StartOfLine(Element* element = nullptr, const size_t sizeOfLine = 0) {
explicit

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/StartOfLine.hpp
> +    };
Почему конструктор определен здесь? Почему не класс? Почему без списка инициализации?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/StartOfLine.hpp
> +            _elementStart = new Element(&sym, &a, &a);
Деструктора нет - потечет память?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/StartOfLine.hpp
> +            size_t a = 0;
Что за переменная a?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/StartOfLine.hpp
> +            char sym = 'x';
Магическая константа?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/element.hpp
> +    Element(const char* value, const size_t* count, const size_t* UserId) : _value(*value), count(*count), UserId(*UserId), isVisible(true), next(nullptr) {};
Указатели могут быть nullptr...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/element.hpp
> +    Element(const char* value, const size_t* count, const size_t* UserId) : _value(*value), count(*count), UserId(*UserId), isVisible(true), next(nullptr) {};
Какой вообще смысл принимать указатели?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/interfaces/element.hpp
> +    Element(const char* value, const size_t* count, const size_t* UserId) : _value(*value), count(*count), UserId(*UserId), isVisible(true), next(nullptr) {};
Какой смысл в конструкторе? Кажется это просто обычная POD-структура.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/src/Command.cpp
> +}
Без контекста непонятно чего за parseString такой.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/src/WorkWithData.cpp
> +// #include "../include/WorkWithData.hpp"
Ненужный комментарий.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/test.cpp
> + #include "include/WorkWithData.hpp"
?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/test.cpp
> +#include <iostream>
??

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/test.cpp
> +}
???

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/test.cpp
> +    std::vector<std::string> neededResults2 = {"l", "e", "k", "\n", "m", "u", "s", "\n", "x", "y", "z", "\n"};
Это что-то типа интеграционного теста? Даже так должно быть какое-то разделение...

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/test.cpp
> +    }
Тупо копипаста.

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/tests_text_editor/Interface.cpp
> +TEST(interface, insert1) {
Что такое interface? Что такое insert1?

2022-12-20 22:13 UTC, Arugaf commented on server_side/text_editor/tests_text_editor/Interface.cpp
> +};
Что тестируется?

2023-12-05 11:55 UTC, closed without merging